### ISSUE TITLE
Samba app should support Chromebooks with ARM

### ISSUE THREAD

**Issue by dskaram** [GoogleChrome/chromeos_network_file_share#4] opened 2016-01-19 16:07 UTC
Due to some NaCl dependencies, the samba port does not fully support ARM based Chromebooks. We need to work with the NaCl team to ensure ARM users can use the app as well.

**Comment by illiminable** [comment] 2016-02-11 22:52
Closing this since there is a workaround by reducing the optimization level of nacl_io.so library. Separately the root cause is being investigated. But this is not blocking.

**Closed by illiminable** 2016-02-11 22:52 UTC
