### ISSUE TITLE
100 MB glibc subdirectory -- could it be smaller?

### ISSUE THREAD

**Issue by fortran77** [GoogleChrome/chromeos_network_file_share#54] opened 2017-03-14 02:39 UTC
I've been alarmed at how big Google Chrome has been becoming lately. With a fair number of extensions added, it's close to a gigabyte.

One of the contributors to this large size is this Network File Share for Chrome OS extension. It includes a 100+-megabyte directory called glibc that contains a libarm and a lib64 subdirectory, which presumably include support for both ARM and Intel architectures. Also, I see a lot of files (e.g.: *.o, *.dep, *.map) that seem to be files that don't normally need to be distributed to the end user.

It would be great if this extension could be made smaller. E.g., by omitting the un-needed *.o etc. files, deleting the un-needed libarm or li64 at install time, stripping debugging symbols, etc. The people who need these can I'm sure figure out how to get them.

**Comment by illiminable** [comment] 2017-06-07 16:58
Dupe of #13

**Closed** 2017-06-07 16:58 UTC
